### ISSUE TITLE
Gpu usage stuck on 4% and never exceeds it

### ISSUE THREAD

**Issue by abasgames** [proteus117/Proot-android#1]
Using zink 
![Screenshot_2022-11-28-10-09-56-554_com termux x11](https://user-images.githubusercontent.com/45899491/204221473-2c883d7e-cd8e-4697-9502-2cd141d63abe.jpg)

**Comment by abasgames** [comment]
It looks like zink is not hardware accelerated ? 
ZINK: warning, this is cpu-based conditional rendering, say bye-bye to fps

Device : poco f1

**Comment by proteus117** [comment]
> It looks like zink is not hardware accelerated ? ZINK: warning, this is cpu-based conditional rendering, say bye-bye to fps
> 
> Device : poco f1

try maybe to compile mesa with these extended arguments

`LDFLAGS='-l:libandroid-shmem.a -llog' meson .. -D platforms=x11,wayland -D gallium-drivers=swrast,virgl,zink -D vulkan-drivers=freedreno -D dri3=enabled  -D egl=enabled  -D gles2=enabled -D glvnd=true -D glx=dri  -D libunwind=disabled -D shared-glapi=enabled -D microsoft-clc=disabled  -D valgrind=disabled -Dprefix=$PREFIX -D gles1=disabled -D freedreno-kgsl=true -D cpp_rtti=false -Dc_args=-Wno-error=incompatible-function-pointer-types -Dbuildtype=release -D llvm=disabled -D osmesa=true`

also look here. you could try to compile this mesa instead https://github.com/Grima04/mesa-turnip-kgsl

and look here:

 https://ivonblog.com/en-us/posts/termux-compile-mesa-driver/

https://github.com/suhan-paradkar/tewmux-disabled/releases

**Comment by abasgames** [comment]
> > It looks like zink is not hardware accelerated ? ZINK: warning, this is cpu-based conditional rendering, say bye-bye to fps
> > Device : poco f1
> 
> try maybe to compile mesa with these extended arguments
> 
> `LDFLAGS='-l:libandroid-shmem.a -llog' meson .. -D platforms=x11,wayland -D gallium-drivers=swrast,virgl,zink -D vulkan-drivers=freedreno -D dri3=enabled -D egl=enabled -D gles2=enabled -D glvnd=true -D glx=dri -D libunwind=disabled -D shared-glapi=enabled -D microsoft-clc=disabled -D valgrind=disabled -Dprefix=$PREFIX -D gles1=disabled -D freedreno-kgsl=true -D cpp_rtti=false -Dc_args=-Wno-error=incompatible-function-pointer-types -Dbuildtype=release -D llvm=disabled -D osmesa=true`
> 
> also look here. you could try to compile this mesa instead https://github.com/Grima04/mesa-turnip-kgsl
> 
> and look here:
> 
> https://ivonblog.com/en-us/posts/termux-compile-mesa-driver/
> 
> https://github.com/suhan-paradkar/tewmux-disabled/releases

In termux or in proot ?
